spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    mode: LEGACY
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  properties:
   hibernate:
    format_sql: true
  security:
   oauth2:
    resourceserver:
     jwt:
      issuer-uri: http://localhost:8080/realms/dev-1
    client:
     registration:
      keycloak:
       client-id: login-app
       client-secret: SXYLSV9ylLGwEdl9M7eICBSLwFqF3Cw6
       client-authentication-method: client_secret_post
       authorization-grant-type: authorization_code
       scope: openid
     provider:
      keycloak:
       issuer-uri: http://localhost:8080/realms/dev-1
       user-name-attribute: preferred_username
    
logging:
 level:
  root: WARN
  org:
   hibernate:
    type: trace
  com:
   example:
    spring_mybatis: TRACE

springdoc:
  swagger-ui:
    path: /

server:
 port: 8081
 
app:
 jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
 jwt-expiration-milliseconds: 3000000